jobs:
- deployment: VMDeploy
  displayName: Deploy SCF To Windows
  environment:
    name:  test-pub-vm
    resourceType: VirtualMachine
    tags: windows,sit
  strategy:
      rolling:
        maxParallel: 5  #for percentages, mention as x%
        preDeploy:
          steps:
          - script: echo initialize, cleanup, backup, install certs
        deploy:
          steps:
          - task: BatchScript@1
            inputs:
              filename: "C:/scripts/download.bat"
          - task: CmdLine@2
            inputs:
              script: 'start C:\jdk-11\bin\java -jar C:\scripts\spring-petclinic-2.6.0-SNAPSHOT.jar'
          
        routeTraffic:
          steps:
          - script: echo routing traffic
        postRouteTraffic:
          steps:
          - script: echo health check post-route traffic
        on:
          failure:
            steps:
            - script: echo Restore from backup! This is on failure
          success:
            steps:
            - script: echo Notify! This is on success