jobs:
- deployment: VMDeploy
  displayName: Deploy SCF To Windows
  environment:
    name:  test-pub-vm
    resourceType: VirtualMachine
    tags: windows
  strategy:
      rolling:
        maxParallel: 5  #for percentages, mention as x%
        preDeploy:
          steps:
          - script: echo initialize, cleanup, backup, install certs
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: 'C:/scripts/downalod-deploy.bat'
        routeTraffic:
          steps:
          - script: echo routing traffic
        postRouteTraffic:
          steps:
          - script: echo health check post-route traffic
        on:
          failure:
            steps:
            - script: echo Restore from backup! This is on failure
          success:
            steps:
            - script: echo Notify! This is on success